global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "woozystudio-app"
    static_configs:
      - targets: ["woozystudio-app:8787"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
